### NER (Named Entity Recognition)

In [1]:
import spacy 

nlp = spacy.load('en_core_web_sm')

sentence = 'Why Apple is looking at buying U.K. startup for $1 billion ?'

doc = nlp(sentence)

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

Apple 4 9 ORG
U.K. 31 35 GPE
$1 billion 48 58 MONEY

In [2]:
# Case Sensitive
sentence = 'Why apple is looking at buying U.K. startup for $1 billion ?'

doc = nlp(sentence)

for ent in doc.ents:
    print(ent.text, ent.label_)

U.K. GPE
$1 billion MONEY

In [ ]:

df = pd.read_csv('Datasets/book_reviews_sample.csv')
df.head()

KeyboardInterrupt:

In [6]:
df = df.rename(columns={
    "reviewText": "Reviews",
    "rating": "Ratings"
})

In [7]:
df.head()

   index                                            Reviews  Ratings
0  11494  Clean and funny. A bit busy with all the diffe...        3
1    984  Alex a sexy hot cop and the PhD candidate. Wha...        4
2   1463  Good thing that this is a free story. I read i...        1
3  10342  Action, action, action! Equipment keeps gettin...        4
4   5256  this was hands down the worse book i have ever...        1

In [ ]:
df[['Reviews', 'Ratings']].to_csv('book_reviews.csv', index=False)

                                             Reviews  Ratings
0  Clean and funny. A bit busy with all the diffe...        3
1  Alex a sexy hot cop and the PhD candidate. Wha...        4
2  Good thing that this is a free story. I read i...        1
3  Action, action, action! Equipment keeps gettin...        4
4  this was hands down the worse book i have ever...        1

In [6]:
import pandas as pd

df = pd.read_csv('book_reviews.csv')
df.head()

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

## 1. NER with Spacy

In [13]:
import spacy

nlp = spacy.load('en_core_web_sm')

for text in df['Reviews'][:20]:
    doc = nlp(text)
    for ent in doc.ents:
        print(f'{ent.text} --> {ent.label_}')

Alex --> PERSON
PhD --> WORK_OF_ART
a few years ago --> DATE
Kinkle --> GPE
Dan --> PERSON
Elle --> PERSON
1 --> CARDINAL

## 2. Sentimental Analysis

In [14]:
# 2.1 TextBlob 
from textblob import TextBlob
text_blob_scores = []

for text in df['Reviews']:
    score = TextBlob(text).sentiment.polarity
    text_blob_scores.append(score)
print(text_blob_scores[:10])

[0.23611111111111108, 0.43, 0.18750000000000003, 0.11534090909090909, -0.2777777777777778, 0.3333333333333333, 0.38, 0.6666666666666666, 0.0, 0.6]

In [16]:
# 2.2 VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vader_scores = []

for text in df['Reviews']:
    score = SentimentIntensityAnalyzer().polarity_scores(text)
    print(score)
    vader_scores.append(score['compound'])

{'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compound': 0.7684}
{'neg': 0.0, 'neu': 0.548, 'pos': 0.452, 'compound': 0.9325}
{'neg': 0.062, 'neu': 0.707, 'pos': 0.231, 'compound': 0.674}
{'neg': 0.0, 'neu': 0.747, 'pos': 0.253, 'compound': 0.6948}
{'neg': 0.162, 'neu': 0.838, 'pos': 0.0, 'compound': -0.4767}
{'neg': 0.193, 'neu': 0.433, 'pos': 0.373, 'compound': 0.75}
{'neg': 0.0, 'neu': 0.858, 'pos': 0.142, 'compound': 0.5106}
{'neg': 0.0, 'neu': 0.731, 'pos': 0.269, 'compound': 0.7906}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.721, 'pos': 0.279, 'compound': 0.8107}
{'neg': 0.0, 'neu': 0.807, 'pos': 0.193, 'compound': 0.5106}
{'neg': 0.198, 'neu': 0.802, 'pos': 0.0, 'compound': -0.5334}
{'neg': 0.084, 'neu': 0.793, 'pos': 0.123, 'compound': 0.2477}
{'neg': 0.0, 'neu': 0.728, 'pos': 0.272, 'compound': 0.7745}
{'neg': 0.136, 'neu': 0.864, 'pos': 0.0, 'compound': -0.4585}
{'neg': 0.323, 'neu': 0.509, 'pos': 0.167, 'compound': -0.4838}
{'neg': 0.091, 'neu': 0.826, 'pos': 0.083, 'compound': -0.0498}
{'neg': 0.0, 'neu': 0.753, 'pos': 0.247, 'compound': 0.7089}
{'neg': 0.0, 'neu': 0.627, 'pos': 0.373, 'compound': 0.8658}
{'neg': 0.171, 'neu': 0.59, 'pos': 0.239, 'compound': 0.4749}
{'neg': 0.076, 'neu': 0.924, 'pos': 0.0, 'compound': -0.1419}
{'neg': 0.0, 'neu': 0.642, 'pos': 0.358, 'compound': 0.8578}
{'neg': 0.116, 'neu': 0.669, 'pos': 0.216, 'compound': 0.4001}
{'neg': 0.0, 'neu': 0.628, 'pos': 0.372, 'compound': 0.8775}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.688, 'pos': 0.312, 'compound': 0.7717}
{'neg': 0.0, 'neu': 0.192, 'pos': 0.808, 'compound': 0.6369}
{'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.8316}
{'neg': 0.23, 'neu': 0.632, 'pos': 0.138, 'compound': -0.3582}
{'neg': 0.063, 'neu': 0.807, 'pos': 0.13, 'compound': 0.3612}
{'neg': 0.122, 'neu': 0.878, 'pos': 0.0, 'compound': -0.3875}
{'neg': 0.123, 'neu': 0.714, 'pos': 0.163, 'compound': 0.25}
{'neg': 0.326, 'neu': 0.674, 'pos': 0.0, 'compound': -0.8038}
{'neg': 0.0, 'neu': 0.868, 'pos': 0.132, 'compound': 0.4404}
{'neg': 0.0, 'neu': 0.806, 'pos': 0.194, 'compound': 0.2323}
{'neg': 0.0, 'neu': 0.828, 'pos': 0.172, 'compound': 0.4404}
{'neg': 0.3, 'neu': 0.7, 'pos': 0.0, 'compound': -0.7719}
{'neg': 0.091, 'neu': 0.64, 'pos': 0.269, 'compound': 0.743}
{'neg': 0.225, 'neu': 0.701, 'pos': 0.073, 'compound': -0.5702}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.487, 'pos': 0.513, 'compound': 0.9413}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'compound': 0.743}
{'neg': 0.0, 'neu': 0.548, 'pos': 0.452, 'compound': 0.9218}
{'neg': 0.086, 'neu': 0.455, 'pos': 0.458, 'compound': 0.847}
{'neg': 0.0, 'neu': 0.9, 'pos': 0.1, 'compound': 0.2732}
{'neg': 0.0, 'neu': 0.565, 'pos': 0.435, 'compound': 0.5927}
{'neg': 0.0, 'neu': 0.616, 'pos': 0.384, 'compound': 0.8745}
{'neg': 0.115, 'neu': 0.601, 'pos': 0.284, 'compound': 0.4749}
{'neg': 0.0, 'neu': 0.711, 'pos': 0.289, 'compound': 0.7264}
{'neg': 0.172, 'neu': 0.828, 'pos': 0.0, 'compound': -0.4404}
{'neg': 0.0, 'neu': 0.656, 'pos': 0.344, 'compound': 0.6369}
{'neg': 0.0, 'neu': 0.815, 'pos': 0.185, 'compound': 0.6486}
{'neg': 0.099, 'neu': 0.901, 'pos': 0.0, 'compound': -0.296}
{'neg': 0.0, 'neu': 0.776, 'pos': 0.224, 'compound': 0.6705}
{'neg': 0.145, 'neu': 0.4, 'pos': 0.455, 'compound': 0.8779}
{'neg': 0.289, 'neu': 0.711, 'pos': 0.0, 'compound': -0.2572}
{'neg': 0.155, 'neu': 0.718, 'pos': 0.127, 'compound': 0.0869}
{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'compound': 0.4404}
{'neg': 0.0, 'neu': 0.826, 'pos': 0.174, 'compound': 0.5859}
{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'compound': 0.5106}
{'neg': 0.134, 'neu': 0.671, 'pos': 0.195, 'compound': 0.3111}
{'neg': 0.131, 'neu': 0.503, 'pos': 0.366, 'compound': 0.7198}
{'neg': 0.0, 'neu': 0.278, 'pos': 0.722, 'compound': 0.3804}
{'neg': 0.0, 'neu': 0.889, 'pos': 0.111, 'compound': 0.3612}
{'neg': 0.15, 'neu': 0.64, 'pos': 0.21, 'compound': 0.201}
{'neg': 0.091, 'neu': 0.909, 'pos': 0.0, 'compound': -0.2755}
{'neg': 0.205, 'neu': 0.675, 'pos': 0.12, 'compound': -0.3149}
{'neg': 0.0, 'neu': 0.725, 'pos': 0.275, 'compound': 0.6486}
{'neg': 0.096, 'neu': 0.677, 'pos': 0.227, 'compound': 0.5106}
{'neg': 0.0, 'neu': 0.714, 'pos': 0.286, 'compound': 0.6369}
{'neg': 0.088, 'neu': 0.522, 'pos': 0.39, 'compound': 0.8176}
{'neg': 0.075, 'neu': 0.735, 'pos': 0.19, 'compound': 0.3945}
{'neg': 0.184, 'neu': 0.816, 'pos': 0.0, 'compound': -0.4717}
{'neg': 0.0, 'neu': 0.878, 'pos': 0.122, 'compound': 0.2714}
{'neg': 0.362, 'neu': 0.638, 'pos': 0.0, 'compound': -0.8428}
{'neg': 0.224, 'neu': 0.591, 'pos': 0.185, 'compound': 0.0}
{'neg': 0.296, 'neu': 0.6, 'pos': 0.103, 'compound': -0.7552}
{'neg': 0.0, 'neu': 0.759, 'pos': 0.241, 'compound': 0.6908}
{'neg': 0.0, 'neu': 0.698, 'pos': 0.302, 'compound': 0.7479}
{'neg': 0.0, 'neu': 0.505, 'pos': 0.495, 'compound': 0.9287}
{'neg': 0.147, 'neu': 0.646, 'pos': 0.207, 'compound': 0.3408}
{'neg': 0.0, 'neu': 0.644, 'pos': 0.356, 'compound': 0.8519}
{'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'compound': 0.7845}
{'neg': 0.15, 'neu': 0.692, 'pos': 0.158, 'compound': 0.0516}
{'neg': 0.245, 'neu': 0.62, 'pos': 0.135, 'compound': -0.25}
{'neg': 0.0, 'neu': 0.444, 'pos': 0.556, 'compound': 0.9628}
{'neg': 0.0, 'neu': 0.809, 'pos': 0.191, 'compound': 0.6688}
{'neg': 0.0, 'neu': 0.629, 'pos': 0.371, 'compound': 0.9123}
{'neg': 0.0, 'neu': 0.881, 'pos': 0.119, 'compound': 0.4019}
{'neg': 0.055, 'neu': 0.419, 'pos': 0.526, 'compound': 0.9485}
{'neg': 0.0, 'neu': 0.905, 'pos': 0.095, 'compound': 0.2732}
{'neg': 0.0, 'neu': 0.68, 'pos': 0.32, 'compound': 0.8162}
{'neg': 0.0, 'neu': 0.647, 'pos': 0.353, 'compound': 0.8237}
{'neg': 0.082, 'neu': 0.774, 'pos': 0.144, 'compound': 0.3851}
{'neg': 0.0, 'neu': 0.83, 'pos': 0.17, 'compound': 0.5994}
{'neg': 0.0, 'neu': 0.814, 'pos': 0.186, 'compound': 0.3147}
{'neg': 0.0, 'neu': 0.635, 'pos': 0.365, 'compound': 0.8686}

In [17]:
bins = [-1, -0.1, 0.1, 1]
names = ['Negative', 'Neutral', 'Positive']
df['textblob_labels'] = pd.cut(text_blob_scores, bins, labels=names)
df['vader_labels'] = pd.cut(vader_scores, bins, labels=names)

In [18]:
df.head()

,Reviews,Ratings,textblob_labels,vader_labels
0,Clean and funny. A bit busy with all the diffe...,3,Positive,Positive
1,Alex a sexy hot cop and the PhD candidate. Wha...,4,Positive,Positive
2,Good thing that this is a free story. I read i...,1,Positive,Positive
3,"Action, action, action! Equipment keeps gettin...",4,Positive,Positive
4,this was hands down the worse book i have ever...,1,Negative,Negative

## 3. Transformer Models - BERT

In [3]:
!pip3 install torch transformers accelerate datasets scikit-learn pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting torch
  Downloading torch-2.8.0-cp39-none-macosx_11_0_arm64.whl (73.6 MB)
     |████████████████████████████████| 73.6 MB 2.8 MB/s eta 0:00:01     |███████████████████████▌        | 54.1 MB 2.4 MB/s eta 0:00:09
Collecting transformers
  Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 2.3 MB/s eta 0:00:01
Collecting accelerate
  Downloading accelerate-1.10.1-py3-none-any.whl (374 kB)
     |████████████████████████████████| 374 kB 2.3 MB/s eta 0:00:01
Collecting datasets
  Downloading datasets-4.4.2-py3-none-any.whl (512 kB)
     |████████████████████████████████| 512 kB 2.3 MB/s eta 0:00:01
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp39-cp39-macosx_12_0_arm64.whl (11.1 MB)
     |████████████████████████████████| 11.1 MB 2.1 MB/s eta 0:00:01
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 328 kB/s eta 0:00:01
Collecting numpy
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 3.2 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/orbinsunny/Library/Python/3.9/lib/python/site-packages (from torch) (4.15.0)
Collecting sympy>=1.13.3
  Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 4.4 MB/s eta 0:00:01�███        | 4.7 MB 4.4 MB/s eta 0:00:01
Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 2.5 MB/s eta 0:00:01
Collecting filelock
  Downloading filelock-3.19.1-py3-none-any.whl (15 kB)
Collecting networkx
  Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 2.5 MB/s eta 0:00:01
Collecting fsspec
  Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 3.0 MB/s eta 0:00:01
Collecting regex!=2019.12.17
  Downloading regex-2025.11.3-cp39-cp39-macosx_11_0_arm64.whl (288 kB)
     |████████████████████████████████| 288 kB 3.1 MB/s eta 0:00:01
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 3.4 MB/s eta 0:00:01
Collecting tqdm>=4.27
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 4.3 MB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in /Users/orbinsunny/Library/Python/3.9/lib/python/site-packages (from transformers) (25.0)
Collecting tokenizers<=0.23.0,>=0.22.0
  Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 2.9 MB/s eta 0:00:01
Collecting safetensors>=0.4.3
  Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
     |████████████████████████████████| 447 kB 5.3 MB/s eta 0:00:01
Collecting pyyaml>=5.1
  Downloading pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
     |████████████████████████████████| 174 kB 5.3 MB/s eta 0:00:01
Collecting huggingface-hub<1.0,>=0.34.0
  Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
     |████████████████████████████████| 566 kB 4.9 MB/s eta 0:00:01
Requirement already satisfied: psutil in /Users/orbinsunny/Library/Python/3.9/lib/python/site-packages (from accelerate) (7.2.1)
Collecting dill<0.4.1,>=0.3.0
  Downloading dill-0.4.0-py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 2.7 MB/s eta 0:00:01
Collecting xxhash
  Downloading xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl (30 kB)
Collecting multiprocess<0.70.19
  Downloading multiprocess-0.70.18-py39-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 2.8 MB/s eta 0:00:01
Collecting pyarrow>=21.0.0
  Downloading pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl (31.2 MB)
     |████████████████████████████████| 31.2 MB 3.6 MB/s eta 0:00:01
Collecting httpx<1.0.0
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 4.1 MB/s eta 0:00:01
Collecting joblib>=1.2.0
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     |████████████████████████████████| 309 kB 5.0 MB/s eta 0:00:01
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting scipy>=1.6.0
  Downloading scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
     |████████████████████████████████| 30.3 MB 1.5 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/orbinsunny/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 2.1 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 2.4 MB/s eta 0:00:01
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.13.3-cp39-cp39-macosx_11_0_arm64.whl (492 kB)
     |████████████████████████████████| 492 kB 2.5 MB/s eta 0:00:01
Collecting attrs>=17.3.0
  Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 3.4 MB/s eta 0:00:01
Collecting aiosignal>=1.4.0
  Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.7.0-cp39-cp39-macosx_11_0_arm64.whl (44 kB)
     |████████████████████████████████| 44 kB 3.3 MB/s eta 0:00:01
Collecting async-timeout<6.0,>=4.0
  Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl (50 kB)
     |████████████████████████████████| 50 kB 3.1 MB/s eta 0:00:01
Collecting propcache>=0.2.0
  Downloading propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl (47 kB)
     |████████████████████████████████| 47 kB 3.3 MB/s eta 0:00:01
Collecting yarl<2.0,>=1.17.0
  Downloading yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl (94 kB)
     |████████████████████████████████| 94 kB 2.5 MB/s eta 0:00:01
Collecting aiohappyeyeballs>=2.5.0
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Collecting anyio
  Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
     |████████████████████████████████| 113 kB 2.6 MB/s eta 0:00:01
Collecting idna
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 3.5 MB/s eta 0:00:01
Collecting certifi
  Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 2.6 MB/s eta 0:00:01
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 3.3 MB/s eta 0:00:01
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting hf-xet<2.0.0,>=1.1.3
  Downloading hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 2.6 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.2-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 3.3 MB/s eta 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp39-cp39-macosx_10_9_universal2.whl (209 kB)
     |████████████████████████████████| 209 kB 3.2 MB/s eta 0:00:01
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     |████████████████████████████████| 536 kB 3.4 MB/s eta 0:00:01
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/orbinsunny/Library/Python/3.9/lib/python/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Collecting MarkupSafe>=2.0
  Downloading markupsafe-3.0.3-cp39-cp39-macosx_11_0_arm64.whl (12 kB)
Installing collected packages: urllib3, propcache, multidict, idna, frozenlist, charset-normalizer, certifi, yarl, tqdm, requests, pyyaml, mpmath, MarkupSafe, hf-xet, h11, fsspec, filelock, attrs, async-timeout, aiosignal, aiohappyeyeballs, tzdata, sympy, pytz, numpy, networkx, jinja2, huggingface-hub, httpcore, dill, anyio, aiohttp, xxhash, torch, tokenizers, threadpoolctl, scipy, safetensors, regex, pyarrow, pandas, multiprocess, joblib, httpx, transformers, scikit-learn, datasets, accelerate
Successfully installed MarkupSafe-3.0.3 accelerate-1.10.1 aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 anyio-4.12.1 async-timeout-5.0.1 attrs-25.4.0 certifi-2026.1.4 charset-normalizer-3.4.4 datasets-4.4.2 dill-0.4.0 filelock-3.19.1 frozenlist-1.8.0 fsspec-2025.10.0 h11-0.16.0 hf-xet-1.2.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-0.36.0 idna-3.11 jinja2-3.1.6 joblib-1.5.3 mpmath-1.3.0 multidict-6.7.0 multiprocess-0.70.18 networkx-3.2.1 numpy-2.0.2 pandas-2.3.3 propcache-0.4.1 pyarrow-21.0.0 pytz-2025.2 pyyaml-6.0.3 regex-2025.11.3 requests-2.32.5 safetensors-0.7.0 scikit-learn-1.6.1 scipy-1.13.1 sympy-1.14.0 threadpoolctl-3.6.0 tokenizers-0.22.2 torch-2.8.0 tqdm-4.67.1 transformers-4.57.3 tzdata-2025.3 urllib3-2.6.2 xxhash-3.6.0 yarl-1.22.0
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [20]:
df.head()

,Reviews,Ratings,textblob_labels,vader_labels
0,Clean and funny. A bit busy with all the diffe...,3,Positive,Positive
1,Alex a sexy hot cop and the PhD candidate. Wha...,4,Positive,Positive
2,Good thing that this is a free story. I read i...,1,Positive,Positive
3,"Action, action, action! Equipment keeps gettin...",4,Positive,Positive
4,this was hands down the worse book i have ever...,1,Negative,Negative

In [22]:
def map_sentiment(rating):
    if rating <=2:
        return 0
    elif rating ==3:
        return 1
    else:
        return 2
    
df['label'] = df['Ratings'].apply(map_sentiment)
df.head()

,Reviews,Ratings,textblob_labels,vader_labels,label
0,Clean and funny. A bit busy with all the diffe...,3,Positive,Positive,1
1,Alex a sexy hot cop and the PhD candidate. Wha...,4,Positive,Positive,2
2,Good thing that this is a free story. I read i...,1,Positive,Positive,0
3,"Action, action, action! Equipment keeps gettin...",4,Positive,Positive,2
4,this was hands down the worse book i have ever...,1,Negative,Negative,0

In [23]:
from transformers import BertTokenizer 

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# tokenize text 
def tokenize(batch):
    return tokenizer(batch['Reviews'], padding='max_length', truncation=True, max_length=128)

In [ ]:
from datasets import Dataset 

dataset = Dataset.from_pandas(df)
dataset = dataset.map(tokenize, batched=True)

Map: 100%|██████████| 100/100 [00:00<00:00, 2140.65 examples/s]

Dataset({
    features: ['Reviews', 'Ratings', 'textblob_labels', 'vader_labels', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 100
})

In [26]:
dataset = dataset.remove_columns(['Reviews', 'Ratings', 'textblob_labels', 'vader_labels'])
dataset

Dataset({
    features: ['label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 100
})

In [27]:
dataset.set_format('torch')

In [28]:
dataset = dataset.train_test_split(test_size=0.2)
train_ds= dataset['train']
test_ds = dataset['test']

In [29]:
from transformers import BertForSequenceClassification 

model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [35]:
!pip install 'accelerate>=0.26.0'

Requirement already satisfied: accelerate>=0.26.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (25.0)
Requirement already satisfied: psutil in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (7.1.1)
Requirement already satisfied: pyyaml in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (2.9.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from accelerate>=0.26.0) (0.6.2)
Requirement already satisfied: filelock in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (2025.9.0)
Requirement already satisfied: requests in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=0.26.0) (1.2.0)
Requirement already satisfied: setuptools in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.26.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.26.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.5)
Requirement already satisfied: jinja2 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=0.26.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate>=0.26.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/orbinsunny/.pyenv/versions/3.12.3/lib/python3.12/site-packages (from requests->huggingface_hub>=0.21.0->accelerate>=0.26.0) (2025.10.5)

In [39]:
!/Users/orbinsunny/.pyenv/versions/3.12.3/bin/python -m pip install --upgrade --force-reinstall accelerate

Collecting accelerate
  Using cached accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.17 (from accelerate)
  Using cached numpy-2.4.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting packaging>=20.0 (from accelerate)
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting psutil (from accelerate)
  Using cached psutil-7.2.1-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting pyyaml (from accelerate)
  Using cached pyyaml-6.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting torch>=2.0.0 (from accelerate)
  Using cached torch-2.9.1-cp312-none-macosx_11_0_arm64.whl.metadata (30 kB)
Collecting huggingface_hub>=0.21.0 (from accelerate)
  Downloading huggingface_hub-1.2.4-py3-none-any.whl.metadata (13 kB)
Collecting safetensors>=0.4.3 (from accelerate)
  Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting filelock (from huggingface_hub>=0.21.0->accelerate)
  Using cached filelock-3.20.2-py3-none-any.whl.metadata (2.1 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub>=0.21.0->accelerate)
  Using cached fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.2.0 (from huggingface_hub>=0.21.0->accelerate)
  Using cached hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub>=0.21.0->accelerate)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting shellingham (from huggingface_hub>=0.21.0->accelerate)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting tqdm>=4.42.1 (from huggingface_hub>=0.21.0->accelerate)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting typer-slim (from huggingface_hub>=0.21.0->accelerate)
  Downloading typer_slim-0.21.1-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface_hub>=0.21.0->accelerate)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting setuptools (from torch>=2.0.0->accelerate)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=2.0.0->accelerate)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=2.0.0->accelerate)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch>=2.0.0->accelerate)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.0.0->accelerate)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=2.0.0->accelerate)
  Using cached markupsafe-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting click>=8.0.0 (from typer-slim->huggingface_hub>=0.21.0->accelerate)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Using cached accelerate-1.12.0-py3-none-any.whl (380 kB)
Downloading huggingface_hub-1.2.4-py3-none-any.whl (520 kB)
Using cached hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl (2.7 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached fsspec-2025.12.0-py3-none-any.whl (201 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached numpy-2.4.0-cp312-cp312-macosx_14_0_arm64.whl (5.2 MB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Using cached pyyaml-6.0.3-cp312-cp312-macosx_11_0_arm64.whl (173 kB)
Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Using cached torch-2.9.1-cp312-none-macosx_11_0_arm64.whl (74.5 MB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Using cached filelock-3.20.2-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp312-cp312-macosx_11_0_arm64.whl (12 kB)
Using cached psutil-7.2.1-cp36-abi3-macosx_11_0_arm64.whl (128 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading typer_slim-0.21.1-py3-none-any.whl (47 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Installing collected packages: mpmath, typing-extensions, tqdm, sympy, shellingham, setuptools, safetensors, pyyaml, psutil, packaging, numpy, networkx, MarkupSafe, idna, hf-xet, h11, fsspec, filelock, click, certifi, typer-slim, jinja2, httpcore, anyio, torch, httpx, huggingface_hub, accelerate
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: typing-extensions━━━━━━━  0/28 [mpmath]
    Found existing installation: typing_extensions 4.15.028 [mpmath]
    Uninstalling typing_extensions-4.15.0:━━  0/28 [mpmath]
      Successfully uninstalled typing_extensions-4.15.0━━━━━━━━━━━  1/28 [typing-extensions]
  Attempting uninstall: tqdm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
    Found existing installation: tqdm 4.67.1━━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
    Uninstalling tqdm-4.67.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
      Successfully uninstalled tqdm-4.67.1━━━━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
  Attempting uninstall: sympy━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
    Found existing installation: sympy 1.14.0━━━━━━━━━━━━━━━━━  1/28 [typing-extensions]
    Uninstalling sympy-1.14.0:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/28 [sympy]ensions]
      Successfully uninstalled sympy-1.14.0━━━━━━━━━━━━━━━━━━━━━━━  3/28 [sympy]
  Attempting uninstall: setuptools━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/28 [sympy]
    Found existing installation: setuptools 80.9.0━━━━━━━━━━━━  3/28 [sympy]
    Uninstalling setuptools-80.9.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
      Successfully uninstalled setuptools-80.9.0━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
  Attempting uninstall: safetensors━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
    Found existing installation: safetensors 0.6.2━━━━━━━━━━━━  5/28 [setuptools]
    Uninstalling safetensors-0.6.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
      Successfully uninstalled safetensors-0.6.2━━━━━━━━━━━━━━  5/28 [setuptools]
  Attempting uninstall: pyyaml━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
    Found existing installation: PyYAML 6.0.3━━━━━━━━━━━━━━━━━  5/28 [setuptools]
    Uninstalling PyYAML-6.0.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
      Successfully uninstalled PyYAML-6.0.3━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
  Attempting uninstall: psutil━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
    Found existing installation: psutil 7.1.1━━━━━━━━━━━━━━━━━  5/28 [setuptools]
    Uninstalling psutil-7.1.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
      Successfully uninstalled psutil-7.1.1━━━━━━━━━━━━━━━━━━━  5/28 [setuptools]
  Attempting uninstall: packaging━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/28 [psutil]
    Found existing installation: packaging 25.0━━━━━━━━━━━━━━━  8/28 [psutil]
    Uninstalling packaging-25.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/28 [psutil]
      Successfully uninstalled packaging-25.0━━━━━━━━━━━━━━━━━  8/28 [psutil]
  Attempting uninstall: numpy━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/28 [psutil]
    Found existing installation: numpy 2.3.4━━━━━━━━━━━━━━━━━━  8/28 [psutil]
    Uninstalling numpy-2.3.4:━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/28 [psutil]
      Successfully uninstalled numpy-2.3.4━━━━━━━━━━━━━━━━━━━━  8/28 [psutil]
  Attempting uninstall: networkx━━━━━━━━━━━━━━━━━━━━━━━━━ 10/28 [numpy]
    Found existing installation: networkx 3.5━━━━━━━━━━━━━━━━━ 10/28 [numpy]
    Uninstalling networkx-3.5:0m━━━━━━━━━━━━━━━━━━━━━━━━━ 10/28 [numpy]
      Successfully uninstalled networkx-3.5━━━━━━━━━━━━━━━━━━━━━━━ 11/28 [networkx]
  Attempting uninstall: MarkupSafe[0m━━━━━━━━━━━━━━━━━━━━━━━━ 11/28 [networkx]
    Found existing installation: MarkupSafe 3.0.3━━━━━━━━━━━━━ 11/28 [networkx]
    Uninstalling MarkupSafe-3.0.3:[90m━━━━━━━━━━━━━━━━━━━━━━━━ 11/28 [networkx]
      Successfully uninstalled MarkupSafe-3.0.3━━━━━━━━━━━━━━━ 11/28 [networkx]
  Attempting uninstall: idna╸━━━━━━━━━━━━━━━━━━━━━━━━ 11/28 [networkx]
    Found existing installation: idna 3.1190m━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Uninstalling idna-3.11:[91m╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
      Successfully uninstalled idna-3.11m━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
  Attempting uninstall: hf-xetm╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Found existing installation: hf-xet 1.2.0━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Uninstalling hf-xet-1.2.0:m╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
      Successfully uninstalled hf-xet-1.2.0━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
  Attempting uninstall: h11[91m╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Found existing installation: h11 0.16.0━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Uninstalling h11-0.16.0:91m╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
      Successfully uninstalled h11-0.16.0━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
  Attempting uninstall: fsspecm╸━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
    Found existing installation: fsspec 2025.9.0━━━━━━━━━━━━━━ 13/28 [idna]
    Uninstalling fsspec-2025.9.0:[0m━━━━━━━━━━━━━━━━━━━━━ 13/28 [idna]
      Successfully uninstalled fsspec-2025.9.0━━━━━━━━━━━━━━━━ 13/28 [idna]
  Attempting uninstall: filelock0m╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
    Found existing installation: filelock 3.20.0━━━━━━━━━━━━━━ 16/28 [fsspec]
    Uninstalling filelock-3.20.0:1m╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
      Successfully uninstalled filelock-3.20.0━━━━━━━━━━━━━━━━ 16/28 [fsspec]
  Attempting uninstall: clickm╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
    Found existing installation: click 8.3.1m━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
    Uninstalling click-8.3.1:m╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
      Successfully uninstalled click-8.3.190m━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
  Attempting uninstall: certifi[91m╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
    Found existing installation: certifi 2025.10.5━━━━━━━━━━━━ 16/28 [fsspec]
    Uninstalling certifi-2025.10.5:╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
      Successfully uninstalled certifi-2025.10.5━━━━━━━━━━━━━━ 16/28 [fsspec]
  Attempting uninstall: typer-slimm╸━━━━━━━━━━━━━━━━━ 16/28 [fsspec]
    Found existing installation: typer-slim 0.20.0━━━━━━━━━━━ 20/28 [typer-slim]
    Uninstalling typer-slim-0.20.0:m╸━━━━━━━━━━━ 20/28 [typer-slim]
      Successfully uninstalled typer-slim-0.20.090m━━━━━━━━━━━ 20/28 [typer-slim]
  Attempting uninstall: jinja2━━╸━━━━━━━━━━━ 20/28 [typer-slim]
    Found existing installation: Jinja2 3.1.6m━━━━━━━━━━━ 20/28 [typer-slim]
    Uninstalling Jinja2-3.1.6:━━╸━━━━━━━━━━━ 20/28 [typer-slim]
      Successfully uninstalled Jinja2-3.1.6[0m━━━━━━━━━━━ 20/28 [typer-slim]
  Attempting uninstall: httpcore╸━━━━━━━━━━━ 20/28 [typer-slim]
    Found existing installation: httpcore 1.0.9[90m━━━━━━━━━━━ 20/28 [typer-slim]
    Uninstalling httpcore-1.0.9:╸━━━━━━━━━━━ 20/28 [typer-slim]
      Successfully uninstalled httpcore-1.0.9m━━━━━━━━━━━ 20/28 [typer-slim]
  Attempting uninstall: anyio━━━━━━━━━━╺━━━━━━━━ 22/28 [httpcore]
    Found existing installation: anyio 4.12.0━━━━━━━━ 22/28 [httpcore]
    Uninstalling anyio-4.12.0:━━━━━╺━━━━━━━━ 22/28 [httpcore]
      Successfully uninstalled anyio-4.12.0m╺━━━━━━━━ 22/28 [httpcore]
  Attempting uninstall: torch━━━━━━╺━━━━━━━━ 22/28 [httpcore]
    Found existing installation: torch 2.9.0╺━━━━━━━━ 22/28 [httpcore]
    Uninstalling torch-2.9.0:━━━━━━━━━━━━━╺━━━━━ 24/28 [torch]
      Successfully uninstalled torch-2.9.0╺━━━━━ 24/28 [torch]
  Attempting uninstall: httpx━━━━━━━━━━━━━╺━━━━━ 24/28 [torch]
    Found existing installation: httpx 0.28.10m╺━━━━━ 24/28 [torch]
    Uninstalling httpx-0.28.1:━━━━━━━━╺━━━━━ 24/28 [torch]
      Successfully uninstalled httpx-0.28.1[90m╺━━━━━ 24/28 [torch]
  Attempting uninstall: huggingface_hub[0m╺━━━━━ 24/28 [torch]
    Found existing installation: huggingface-hub 0.36.00m━━━━━ 24/28 [torch]
    Uninstalling huggingface-hub-0.36.0:0m╺━━━━━ 24/28 [torch]
      Successfully uninstalled huggingface-hub-0.36.0[90m━━━━━ 24/28 [torch]
  Attempting uninstall: accelerate━━━━━━━━━━━╺━━ 26/28 [huggingface_hub]
    Found existing installation: accelerate 1.12.0╺━━ 26/28 [huggingface_hub]
    Uninstalling accelerate-1.12.0:━━━━━━╺━━ 26/28 [huggingface_hub]
      Successfully uninstalled accelerate-1.12.00m╺━━ 26/28 [huggingface_hub]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28/28 [accelerate]8 [accelerate]]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.24.0 requires torch==2.9.0, but you have torch 2.9.1 which is incompatible.
datasets 4.4.1 requires fsspec[http]<=2025.10.0,>=2023.1.0, but you have fsspec 2025.12.0 which is incompatible.
transformers 4.57.1 requires huggingface-hub<1.0,>=0.34.0, but you have huggingface-hub 1.2.4 which is incompatible.
Successfully installed MarkupSafe-3.0.3 accelerate-1.12.0 anyio-4.12.1 certifi-2026.1.4 click-8.3.1 filelock-3.20.2 fsspec-2025.12.0 h11-0.16.0 hf-xet-1.2.0 httpcore-1.0.9 httpx-0.28.1 huggingface_hub-1.2.4 idna-3.11 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 numpy-2.4.0 packaging-25.0 psutil-7.2.1 pyyaml-6.0.3 safetensors-0.7.0 setuptools-80.9.0 shellingham-1.5.4 sympy-1.14.0 torch-2.9.1 tqdm-4.67.1 typer-slim-0.21.1 typing-extensions-4.15.0

In [40]:
import accelerate
print(accelerate.__version__)

1.12.0

In [1]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./bert_sentimnet',
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    learning_rate=2e-5,
    weight_decay=0.01
)

ModuleNotFoundError: No module named 'transformers'

## 4. GPT

## 5. Sequence Models - LSTM

## 6. Translation

Rest of the code

https://colab.research.google.com/drive/1Ko2krNyfl1aGSPQW5bxt9RXVQyfb6Psp